### ISSUE TITLE
Can't parse llvm Core.h

### ISSUE THREAD

**Issue by windrunner414** [ircmaxell/php-c-parser#1]
```
PHPCParser\Error: Syntax error, unexpected IDENTIFIER(__gwchar_t), expecting ',' or ';' on line 393 in /home/parallels/PhpstormProjects/pphp/vendor/ircmaxell/php-c-parser/lib/ParserAbstract.php:235
Stack trace:
#0 /home/parallels/PhpstormProjects/pphp/vendor/ircmaxell/php-c-parser/lib/ParserAbstract.php(104): PHPCParser\ParserAbstract->doParse()
#1 /home/parallels/PhpstormProjects/pphp/vendor/ircmaxell/php-c-parser/lib/CParser.php(23): PHPCParser\ParserAbstract->parse(Array, Object(PHPCParser\Context))
#2 /home/parallels/PhpstormProjects/pphp/vendor/ircmaxell/ffime/lib/FFIMe.php(101): PHPCParser\CParser->parse('llvm-c/Core.h', Object(PHPCParser\Context))
#3 /home/parallels/PhpstormProjects/pphp/tool/GenerateLLVMFFiCode.php(14): FFIMe\FFIMe->include('llvm-c/Core.h')
#4 /home/parallels/PhpstormProjects/pphp/tool/Common.php(27): {closure}()
#5 /home/parallels/PhpstormProjects/pphp/tool/GenerateLLVMFFiCode.php(32): run(Object(Closure), 'building llvm f...')
#6 {main}
```

**Comment by ircmaxell** [comment]
I've hit that in the past. It's because it's assuming there's a built in type `gwchar_t` somewhere in the OS standard lib. Can you provide which OS/libc version you're using?

**Comment by windrunner414** [comment]
macos 10.13.6
